version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5200:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_PUBLIC_ENDPOINT=${MINIO_PUBLIC_ENDPOINT}
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=video-storage
      - MINIO_SECURE=False

  worker:
    build: .
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A celery_worker worker --loglevel=info -c 2
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERYD_MAX_TASKS_PER_CHILD=100
      - MINIO_ENDPOINT=minio:9000
      - MINIO_PUBLIC_ENDPOINT=${MINIO_PUBLIC_ENDPOINT}
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=video-storage
      - MINIO_SECURE=False
    extra_hosts:
      - "host.docker.internal:host-gateway"

  flower:
    build: .
    restart: always
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    depends_on:
      - redis
      - worker
    command: celery -A celery_worker flower --port=5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_PUBLIC_ENDPOINT=${MINIO_PUBLIC_ENDPOINT}
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=video-storage
      - MINIO_SECURE=False

  redis:
    restart: always
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    restart: always
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

volumes:
  minio_data: